Catkin-ProjectName: tod
Version: 0.2.3
Description: Textured Object Recognition a standard bag of features approach

Author: Vincent Rabaud <vrabaud@willowgarage.com>, Ethan Rublee <erublee@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: catkin,

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

